name: sqflite_repo
description: Sqflite repo
version: 0.1.0
homepage: https://github.com/tekartik/sqflite
publish_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  pedantic: '>=1.4.0 <3.0.0' # dart.dev
  tekartik_travis_ci_flutter: # DONE: secure code reviewed 83a30d52752e616c1a9aef9e90482358809caae9
    git:
      url: git://github.com/KomodoPlatform/travis_ci_flutter.dart
      ref: 83a30d52752e616c1a9aef9e90482358809caae9
  process_run: # 0.10.8 - DONE: secure code reviewed 129f744d0b9b6e71cd78cd8207abda0e33c01570 (0.10.8)
    git:
      url: git://github.com/KomodoPlatform/process_run.dart.git
      ref: 129f744d0b9b6e71cd78cd8207abda0e33c01570

dependency_overrides:
  pedantic: '>=1.9.0 <3.0.0' # dart.dev
